# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cybersecurity/UbuntuVM"
  config.vm.hostname = "ucibox"
  config.vm.synced_folder	"../../",	"/vagrant", owner: "2001", group: "2001"
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1", auto_correct: true
  config.vm.network "forwarded_port", guest: 3389, host: 3389, host_ip: "127.0.0.1", auto_correct: true
  config.vm.network "forwarded_port", guest: 5901, host: 5901, host_ip: "127.0.0.1", auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # Uncomment ONE the lines below to control how much RAM Vagrant gives the VM
    # We recommend starting with 4096 (4Gb), and moving down if necessary
    # vb.memory = "1024" # 1Gb
    # vb.memory = "2048" # 2Gb
    # vb.memory = "4096" # 4Gb
    vb.name = "UCIBox"
    vb.gui = true
    vb.customize ['modifyvm', :id, '--vrde', 'on']
    vb.customize ['modifyvm', :id, '--vrdeport', '5002']
    vb.customize ['modifyvm', :id, '--graphicscontroller', 'vboxsvga']
    #vb.customize ['modifyvm', :id, '--firmware', 'efi64']
  end
   config.vm.provision "shell", inline: <<-SHELL
     apt update
     find /vagrant

     file /vagrant/functions/ready | grep CRLF && dos2unix -n /vagrant/functions/ready /usr/local/bin/ready
     file /vagrant/functions/ready | grep CRLF || cp /vagrant/functions/ready /usr/local/bin/ready
     chmod 0700 /usr/local/bin/ready
     ready

     #apt install -yq xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils
     #apt install -yq xrdp
     #systemctl status xrdp
     #adduser xrdp ssl-cert
     #systemctl enable xrdp
     #systemctl restart xrdp
     #apt-get autoremove -yq
     #apt-get upgrade -yq
     #apt-get autoremove -yq
     #apt-get install -yq apache2 make containerd docker docker.io net-tools ansible dos2unix supervisor xrdp # xorg-video-abi-23
     #apt-get install -yq xrdp xorgxrdp-hwe-18.04 xfce4 xfce4-session
     #apt-get autoremove -yq
     #apt-get install -yq xfce4 xfce4-session xrdp
     iptables -F
     iptables -X
     iptables -P INPUT ACCEPT
     iptables -P OUTPUT ACCEPT
     iptables -P FORWARD ACCEPT
     #adduser xrdp ssl-cert
     #echo "unset DBUS_SESSION_BUS_ADDRESS" >> /etc/profile
     #echo "unset XDG_RUNTIME_DIR" >> /etc/profile
     #. $HOME/.profile
     #echo 'xfce4-session' > /home/vagrant/.xsession
     #echo 'xfce4-session' > /home/sysadmin/.xsession
     #echo 'allowed_users=anybody' > /etc/X11/Xwrapper.config

     #systemctl restart xrdp
     setup_vnc
SHELL
end