#!/usr/bin/env bash

CONTAINER_NAME=${1}

#  Script that stops a running container.

function rm () {
	while :
	do
	  docker ps | grep ${CONTAINER_NAME} && docker stop ${CONTAINER_NAME}
	  docker ps | grep ${CONTAINER_NAME} || exit
	  sleep 30
	done
}

rm