#!/usr/bin/env bash

CONTAINER_NAME=${1}

#  Script that stops a running container.

function rm () {
	while :
	do
	  docker ps -a | grep ${CONTAINER_NAME} && docker rm ${CONTAINER_NAME}
	  docker ps -a | grep ${CONTAINER_NAME} || exit
	  sleep 30
	done
}

container-stop ${CONTAINER_NAME}
rm