#!/usr/sbin/env bash

export GIT_SSH_COMMAND="ssh -F ~/galaxy3/spicerack/.ssh/config"

case $(hostname) in

  "naboo") export G3HOME=/vagrant
    ;;

ecase

export SVCROOT=${G3HOME}/svc/

env | egrep GIT_SSH_COMMAND
