#!/usr/sbin/env bash

case $(hostname) in

  naboo|endor)
    export G3HOME=/thedr
    export SVCROOT=${G3HOME}/svc
    ;;
esac

export GIT_SSH_COMMAND="ssh -F ${G3HOME}/spicerack/.ssh/config"
export G3GITHUB=https://github.com/galaxy3-net/
