#!/usr/bin/env bash

DIRNAME=$(dirname ${0})
SCRIPTNAME=$(basename ${0})
SERVICENAME=${1}

function enable () {
  ls /repo/${SERVICENAME}/usr/sbin/${SERVICENAME} && cp /repo/${SERVICENAME}/usr/sbin/${SERVICENAME} /usr/sbin/.
  ls /repo/${SERVICENAME}/etc/supervisor/conf.d/${SERVICENAME}.conf && cp /repo/${SERVICENAME}/etc/supervisor/conf.d/${SERVICENAME}.conf /etc/supervisor/conf.d/.
  supervisorctl reload
}

function disable () {
  ls /etc/supervisor/conf.d/${SERVICENAME}.conf && rm /etc/supervisor/conf.d/${SERVICENAME}.conf
  supervisorctl stop ${SERVICENAME}
  supervisorctl remove ${SERVICENAME}
  #supervisorctl reload
  ls ${SVCROOT:-undefined}/${SERVICENAME}/usr/sbin/${SERVICENAME}.disable.post \
    && bash -c "${SVCROOT:-undefined}/${SERVICENAME}/usr/sbin/${SERVICENAME}.disable.post"
}

case ${SCRIPTNAME} in

  g3enable) enable
          ;;

  g3disable) disable
          ;;

  *) echo "unknown arg"
    exit 1
    ;;
esac
