#!/usr/bin/env bash

set -x
[ -x /vagrant/bin/g3common ] && . /vagrant/bin/g3common

DIRNAME=$(dirname ${0})
SCRIPTNAME=$(basename ${0})
SERVICENAME=${1}

function enable () {
  set -x
  echo enabling ${SERVICENAME}
  ls ${SVCROOT:-undefined}/${SERVICENAME}/usr/sbin/${SERVICENAME} && cp ${SVCROOT:-undefined}/${SERVICENAME}/usr/sbin/${SERVICENAME} /usr/sbin/.
  ls ${SVCROOT:-undefined}/${SERVICENAME}/etc/supervisor/conf.d/${SERVICENAME}.conf && cp ${SVCROOT:-undefined}/${SERVICENAME}/etc/supervisor/conf.d/${SERVICENAME}.conf /etc/supervisor/conf.d/.
  ls /usr/sbin/${SERVICENAME} && chmod u+x /usr/sbin/${SERVICENAME}
  supervisorctl reload
}

function disable () {
  set -x
  echo enabling ${SERVICENAME}
  ls /etc/supervisor/conf.d/${SERVICENAME}.conf && rm /etc/supervisor/conf.d/${SERVICENAME}.conf
  supervisorctl reload
}

case ${SCRIPTNAME} in

  g3enable)
    get_svc ${SERVICENAME:-undefined} ${SERVICENAME:-undefined}:galaxy3-net/${SERVICENAME:-undefined}.git master
    enable
    ;;

  g3disable) disable
          ;;

  *) echo "unknown arg"
    exit 1
    ;;
esac

