#!/usr/bin/env bash
set -x
export BRANCH=thedr
export RAWPATH=https://raw.githubusercontent.com/galaxy3-net/spicerack/${BRANCH}/
export GITPATH=https://github.com/galaxy3-net/spicerack.git

ls ~/galaxy3/spicerack  || get_spicerack
ls ~/galaxy3/spicerack  &&  cd ~/galaxy3/spicerack  &&  git checkout ${BRANCH}  &&  git pull


# ls ~/galaxy3/spicerack  ||

exit
     cat <<__EOD__

     Setting up configuration files to hold the eggs.

     $(pwd)

__EOD__

     cd ~/.ssh && wget -nc ${RAWPATH}/.ssh/config
     cd ~/.ssh/config.d/ && wget -nc ${RAWPATH}/.ssh/config.d/eggs.config

     #cd ~/.ssh/config.d/ && wget -nc ${RAWPATH}/.ssh/config.d/blueprints.config
     #cd ~/.ssh/config.d/ && wget -nc ${RAWPATH}/.ssh/config.d/quarren.config

     printf "\n\n\tGetting the primary egg\n\n"
     file /vagrant/egg | grep CRLF && dos2unix -n /vagrant/egg ~/.ssh/egg
     file /vagrant/egg | grep CRLF || cp /vagrant/egg ~/.ssh/egg
     chmod 0700 ~/.ssh/egg

	printf "\n\n\yGetting the basket\n"
    ls -dl ~/eggs/ 2>/dev/null || (cd ~ && git clone eggs:galaxy3-net/eggs.git)
    (cd ~/eggs/ && git pull)

    ls ~/spicerack || (cd ~/ && git clone ${GITPATH})
    (cd ~/spicerack && git checkout ${BRANCH} && git pull)

    cd ~/eggs
    for egg in $(ls)
    do
      cp ${egg} ~/.ssh/${egg}.egg
      chmod 0700 ~/.ssh/${egg}.egg
    done


    cd ~/spicerack/
    scp -r ~/spicerack/.ssh/ ~/
    #for spice in spicerack
    #do
    #  cp ${spice} ~/.ssh/config.d/${spice}
    #done
    printf "\n\n\tStashing the eggs.\n"
    #ls -dl ~/.ssh/named.egg 2>/dev/null || cp /thedr/eggs/named /thedr/.ssh/named.egg
    #ls -dl ~/.ssh/blueprints.egg 2>/dev/null || cp /thedr/eggs/blueprints /thedr/.ssh/blueprints.egg
    #ls -dl ~/.ssh/quarren.egg 2>/dev/null || cp /thedr/eggs/quarren /thedr/.ssh/quarren.egg

    #chmod 0700 ~/.ssh/*