#!/usr/bin/env bash

export MACHINE=${1:-undefined}

function pull_spicerack () {
  REPO_PATH=https://github.com/galaxy3-net/spicerack.git
  DEST=~/galaxy3/spicerack
  ls -dl ${DEST} 2>/dev/null || bash -c "cd $(dirname ${DEST}) && git clone ${REPO_PATH} && git checkout thedr"
  cd ${DEST} && git checkout thedr && git pull
}

pull_spicerack

REPO_PATH=${MACHINE:-undefined}:galaxy3-net/${MACHINE:-undefined}.git

ls -dl ${HOME}/galaxy3/${REPO} 2>/dev/null || cd ${HOME}/galaxy3 ; git clone ${REPO_PATH}
cd ${HOME}/galaxy3/${REPO} && git pull && git checkout ${2:=${MACHINE}}
