#!/usr/bin/env bash

get_machine naboo
export MACHINE=${1:-undefined}

#REPO=${1}
[ "${2:-undefined}" == "undefined" ] BRANCH=${3}
REPO_PATH=${MACHINE:-undefined}:galaxy3-net/${MACHINE:-undefined}.git

ls -dl ${HOME}/galaxy3/${REPO} 2>/dev/null || cd ${HOME}/galaxy3 ; git clone ${REPO_PATH}
cd ${HOME}/galaxy3/${REPO} && git pull && git checkout ${2:=${MACHINE}}
