#!/usr/bin/env bash

echo "${0}"

cat <<__EOD__

  Creating user thedr


__EOD__


    useradd -d /thedr -c thedr -m -s /bin/bash -u 2001 -U thedr
    # ln -s /vagrant/spicerack/
    #mkdir -p /thedr/.ssh/config.d
    mkdir -p /thedr/{.ssh,galaxy3}

    chown -R thedr:thedr /thedr/
    chmod -R 0700 /thedr/.ssh/
    # ls ~/galaxy3 || ln -s /vagrant ~/galazy3

    cat <<__EOD__ >> /etc/profile
###  G3 Section  ###
. /usr/local/bin/g3common
__EOD__

    su - thedr -c gather_eggs