#!/bin/bash

function mk_thedr () {
    useradd -d /thedr -c thedr -m -s /bin/bash -u 2001 -U thedr
    mkdir -p /thedr/.ssh/config.d

    chown -R thedr:thedr /thedr/
    chmod -R 0700 /thedr/.ssh/
}

userexists thedr || mk_thedr
echo "export G3HOME=~/galaxy3" >> /etc/profile
echo "export G3GITHUB=https://github.com/galaxy3-net/" >> /etc/profile

su - thedr -c gather_eggs