#!/usr/bin/env bash

echo 'Convert functions'
cd /vagrant/functions

for file in $(ls)
do
  tr -d '\r' <${file} >/vagrant/functions/${file} /usr/local/bin/${file}
  chmod 0755 /usr/local/bin/${file}
  ls -adl /usr/local/bin/${file}
done
