#!/usr/bin/env bash

DIRNAME=$(dirname ${0})
SCRIPTNAME=$(basename ${0})
SERVICENAME=${1}

function enable () {
  ls /repo/${SERVICENAME}/usr/sbin/${SERVICENAME} && cp /repo/${SERVICENAME}/usr/sbin/${SERVICENAME} /usr/sbin/.
  ls /repo/${SERVICENAME}/etc/supervisor/conf.d/{SERVICENAME}.conf && cp /repo/${SERVICENAME}/etc/supervisor/conf.d/{SERVICENAME}.conf /etc/supervisor/conf.d/.
  supervisorctl reload
}

function disable () {
  ls /etc/supervisor/conf.d/{SERVICENAME}.conf && rm /etc/supervisor/conf.d/{SERVICENAME}.conf
  supervisorctl reload
}

case ${SCRIPTNAME} in

  enable) enable
          ;;

  disable) disable
          ;;

  *) echo "unknown arg"
    exit 1
    ;;
esac
